### PR TITLE
Workaround to make FASTRTPS test work with two processes

### PR DESCRIPTION
**Pull request by ahcorde**
Changes suggested by @EduPonz 

The issue with the `roundtrip_mode` is that the mode postfixes are not appended correctly, meaning that the postfixes are appended to the topicDataType instead of the the topicName.

However, there is another problem that may arise sometimes when running this mode; that is that the test does not close on `max_time` reached. This is because `FastRTPSCommunicator::update_subscription()` calls to `m_subscriber->waitForUnreadMessage()`, which blocks with a timeout of one day. There are two solutions for this:
 - Substitute waitForUnreadMessage() with the underlying SubscriberImpl::wait_for_unread_samples(const Duration_t& timeout), setting a shorter timeout.
 - Use the python script to kill the executable when the timeout is reached.

I choosed the first option, to kill the process in the launch file https://github.com/ros2/buildfarm_perf_tests/pull/26/commits/6aec12d38e6ea71a11b4b62e86272e1a1c618f9c

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by cottsay** [comment]
> The issue with the roundtrip_mode is that the mode postfixes are not appended correctly, meaning that the postfixes are appended to the topicDataType instead of the the topicName.

Is this a bug in Fast-RTPS itself? Is there something tracking it upstream?

> This is because ... blocks with a timeout of one day.

Ouch. Where is the bug here? Is this a `performance_test` problem in async mode, or another Fast-RTPS-specifc issue?

**Comment by ahcorde** [comment]
>   This is because ... blocks with a timeout of one day.

this commit solved this issue https://github.com/ros2/performance_test/pull/6/commits/e92d3e70de59ce7aef0a3812fc964a0a776f5f3d

Yes, It's a RTPS-specifc issue. It's in the fast_rtps_communicator.hpp file

> Is this a bug in Fast-RTPS itself? Is there something tracking it upstream?

Not really sure, maybe @EduPonz can add here more background

**Comment by EduPonz** [comment]
Hi @ahcorde @cottsay ,

> > The issue with the roundtrip_mode is that the mode postfixes are not appended correctly, meaning that the postfixes are appended to the topicDataType instead of the the topicName.
> 
> Is this a bug in Fast-RTPS itself? Is there something tracking it upstream?

I consider this a bug in `performance_test`, specifically in `fast_rtps_communicator.hpp`. It simply was registering one data type, and then creating publishers and subscribers with un-registered data types. The postfixes were just needed to be appended to the topic name instead of to the data type, as @ahcorde did. Unfortunately, I have not had the to push the fix upstream to Apex's repo.

> > This is because ... blocks with a timeout of one day.
>
> Ouch. Where is the bug here? Is this a `performance_test` problem in async mode, or another Fast-RTPS-specifc issue?

Again, I don't think this is a bug in Fast-RTPS, it is a simple miss used of the API. @ahcorde change will simply break the wait every 3 seconds no matter what, then the `takeNextData` will return False. The important thing here is that once outside the wait, the subscriber can be destroyed (either when timeout or `ctrl-c`).  I have tested this and it works flawlessly :+1: .

> I choosed the first option, to kill the process in the launch file [ros2/buildfarm_perf_tests@6aec12d](https://github.com/ros2/buildfarm_perf_tests/commit/6aec12d38e6ea71a11b4b62e86272e1a1c618f9c)

Actually, I think that killing from the outside is not needed any more. It will exit after a max of 3 seconds no matter what.

**Comment by ahcorde** [comment]
PR created https://gitlab.com/ApexAI/performance_test/-/merge_requests/152

**Pull request merged**
