### PR TITLE
Remove testing of Struct32k.

### PR DESCRIPTION
**Pull request by clalancette**
Current CycloneDDS can't support it, so just remove it for now.
Once we update to later version of CycloneDDS that can support
it, we can revert this commit.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

@Blast545 This should fix the build regressions as seen in https://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_focal_amd64/485/console .

### CODE REVIEW

**Review by Blast545 — APPROVED** [review]
LGTM!

**Review by Blast545 — APPROVED** [review]

**Comment by Blast545** [comment]
Overlay Rci job with the same parameters as the `Rci__nightly-performance_ubuntu_focal_amd64 performance` job 
[Build Status](https://build.ros2.org/view/Rci/job/Rci__overlay_ubuntu_focal_amd64/38/) (timeout)

**Comment by Blast545** [comment]
Overlay Rci job with the same parameters as the, same repos file which the first one differed.

[Build Status](https://build.ros2.org/view/Rci/job/Rci__overlay_ubuntu_focal_amd64/39/)

**Comment by Blast545** [comment]
Prior to the build regression, the "normal" state of that job in the buildfarm was yellow. So for I would say it's good to be merged as is.

**Comment by clalancette** [comment]
Going ahead and merging this with the yellow CI job.

**Pull request merged**
