### PR TITLE
Add larger message types

### PR DESCRIPTION
**Pull request by ivanpauno**
Adds:
- Array4m (which was partially added before)
- Array8m
- PointCloud8m (partially added before)

`boost::mpl::list` is surprisingly limited to 20 types, so I replaced it with a `std::tuple` and custom template magic.

### CODE REVIEW

**Comment by ivanpauno** [comment]
@ahcorde @cottsay The idea of this is to add larger messages and use them in our nightly performance test job, as many of the DDS vendors we support have a pretty bad out of the box performance with large messages.

I'm not sure of how changes in this repo are testes, so please let me know how to proceed. Thanks!

**Comment by ivanpauno** [comment]
> we should contribute these changes upstream too

Opened https://gitlab.com/ApexAI/performance_test/-/merge_requests/160.
Do I have to run a CI job before merging this? In that case, which one?

**Comment by cottsay** [comment]
> Do I have to run a CI job before merging this?

I think the CI upstream should be sufficient. Looks like it failed there, though.

**Comment by ivanpauno** [comment]
> > Do I have to run a CI job before merging this?
> 
> I think the CI upstream should be sufficient. Looks like it failed there, though.

`build_opendds` job failed, for reasons that don't seem to be related.
The other passed, but test jobs where skipped (as one of the build jobs failed).
I don't have opendds available to check what happened.

**Comment by cottsay** [comment]
> `build_opendds` job failed, for reasons that don't seem to be related.

Your other PR passed, so it must be related to your change or it's flaky somehow.

**Comment by ivanpauno** [comment]
@cottsay upstream pipeline is passing https://gitlab.com/ivanpauno/performance_test/pipelines/145780258, can this be merged?

**Comment by ivanpauno** [comment]
Re-targeted PR to `run_on_buildfarm` branch.
Upstream CI is green.

**Pull request merged**
