### PR TITLE
Merge branch 'master' into run_on_buildfarm

### PR DESCRIPTION
**Pull request by cottsay**
We've diverged from the upstream repository a fair bit, but because many of the changes made in this fork were also submitted upstream, the merge wasn't as bad as I thought it would be.

One notable change in behavior coming in from upstream is that the standalone DDS support is now disabled by default. Before merging this, we'll need to add the following cmake arguments to our automated builds:
- `-DPERFORMANCE_TEST_CYCLONEDDS_ENABLED=ON`
- `-DPERFORMANCE_TEST_FASTRTPS_ENABLED=ON`

I triggered an overlay job to test for regressions and demonstrate improvements in the linter failures:
- Rolling: [Build Status](http://build.ros2.org/view/Rci/job/Rci__overlay_ubuntu_focal_amd64/4/)
- Foxy: [Build Status](http://build.ros2.org/view/Fci/job/Fci__overlay_ubuntu_focal_amd64/35/)
- Eloquent: [Build Status](http://build.ros2.org/view/Eci/job/Eci__overlay_ubuntu_bionic_amd64/48/)

For comparison, here are baseline builds of the performance job:
- Rolling: [Build Status](http://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_focal_amd64/105/)
- Foxy: [Build Status](http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64/126/)
- Eloquent: [Build Status](http://build.ros2.org/view/Eci/job/Eci__nightly-performance_ubuntu_bionic_amd64/286/) [Build Status](http://build.ros2.org/view/Eci/job/Eci__overlay_ubuntu_bionic_amd64/49/)

Dashing builds from a separate branch - the `run_on_buildfarm` branch covers Eloquent and newer.

I'm still expecting to see a CMake warning coming out of `performance_test` that isn't remedied by this change. I'm open to suggestions on if there is a way to work around the issue without the need to submit a change upstream:
```
CMake Warning at src/idlgen/fast_rtps/CMakeLists.txt:71 (message):
  Could not find program 'fastrtpsgen' in path.  Trying to use bundled
  version
```

This leaves only three commits absent from upstream. If they were to be merged, we could delete this fork.
- 4a50334 ([upstream PR](https://gitlab.com/ApexAI/performance_test/-/merge_requests/121))
- e2ee644
- ef878b3 ([upstream PR](https://gitlab.com/ApexAI/performance_test/-/merge_requests/129))

### CODE REVIEW

**Comment by dirk-thomas** [comment]
> This leaves only three commits absent from upstream. If they were to be merged, we could delete this fork.

Are there PRs against upstream for these changes?

**Comment by cottsay** [comment]
> Are there PRs against upstream for these changes?

Two of them have outstanding PRs, which I added to the description above. I'm not sure what the status of the third one is - maybe @EduPonz can comment on why that change hasn't (entirely) been merged upstream, or if it is still necessary.

**Comment by dirk-thomas** [comment]
I don't know enough about this repo for a formal approval. But :+1: if this gets us closer to upstream and/or fixes outstanding issues.

**Comment by EduPonz** [comment]
> Two of them have outstanding PRs, which I added to the description above. I'm not sure what the status of the third one is - maybe @EduPonz can comment on why that change hasn't (entirely) been merged upstream, or if it is still necessary.

About the change without PR; those changes were addressed by @ahcorde [here](https://gitlab.com/ApexAI/performance_test/-/commit/ab30932198598dedeb20b53cf969dd55e1152aa4). The exception is the change in `waitForUnreadMessage()`. Around March the 10th, @ahcorde and I discussed the matter, back then I my answer was
```
As I suspected, the problem with the roundtrip_mode is that the mode postfixes are not appended correctly, meaning that the postfixes are appended to the topicDataType instead of the the topicName.
I am attaching a patch to solve the problem.

However, there is another problem that may arise sometimes when running this mode; that is that the test does not close on max_time reached.
This is because FastRTPSCommunicator::update_subscription() calls to m_subscriber->waitForUnreadMessage(), which blocks with a timeout of one day.
There are two solutions for this:
    1. Substitute waitForUnreadMessage() with the underlying SubscriberImpl::wait_for_unread_samples(const Duration_t& timeout), setting a shorter timeout.
    2. Use the python script to kill the executable when the timeout is reached.
```

Upstream, they use python to kill the processes, which goes around the issue. However, I think that it better to do it the way it's done here, so the subscriber only block for 3 seconds at a time. I do not know why this was not added upstream.

Around that date, we also found some issues when using the framework for SHM transport. I wrote an [issue](https://gitlab.com/ApexAI/performance_test/-/issues/108) and provided a quick patch to APEX.AI, but I haven't heard from them since. I think it'd be good to incorporate something on those lines as well.

Sorry I've been absent from this project for some time now. I currently do not have time to work on it, but feel free to ping me any time. I'd be happy to help!

**Review by ahcorde — APPROVED** [review]

**Comment by cottsay** [comment]
Thanks for the detailed explanation, @EduPonz. Sounds like we may have sufficient information now to try to push the change upstream.

The tests came back looking really great, so I'm going to go ahead and merge this.

**Pull request merged**
