### PR TITLE
Make linters happy

### PR DESCRIPTION
**Pull request by chapulina**
Locally, `colcon test` is now successful.

Running CI to see how far it goes, we may need to tweak some dependencies:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5297/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2051/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4415/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5278/)

### CODE REVIEW

**Comment by chapulina** [comment]
Added missing dependency on https://github.com/ros2/performance_test/pull/1/commits/8d4ed8a7f32b74c46d65d0ae88a0221d8661d079, running CI again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5298/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2052/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4416/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5279/)

**Comment by chapulina** [comment]
Ok, I just realized there's a dependency on Boost. I'll keep dependency updates which fix CI for a future PR.

**Comment by mjcarroll** [comment]
I killed the windows build that was hanging, but given that everything else was failing, I'm not confident that it would have passed anyways.

**Comment by chapulina** [comment]
Thanks for killing the build, @mjcarroll . I'm working on a new PR to fix the dependencies and hopefully pass CI.

**Comment by chapulina** [comment]
Thanks for the comment, @deeplearningrobotics. I reverted the cast for now, since it's not related to the linters and there are multiple other similar compiler warnings still present, so that can be tackled in the future.

In any case, your suggestion failed to compile as is:

~~~
error: no matching function for call to 'std::chrono::duration<long int>:
:duration(std::__success_type<std::chrono::duration<long int, std::ratio<1, 1000000000> > >::typ
e)'                                                                                             
     std::chrono::duration<int64_t>(std::chrono::steady_clock::now() - experiment_start).count()
;    
~~~

I also opened the same PR against the Apex repo, in case you peeps get to it first: https://github.com/ApexAI/performance_test/pull/19

**Pull request merged**
